name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main  # Change this if using a different branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v14
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Ionic Angular App
        run: npm run build --prod  # Adjust for your Angular build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
